// Jenkinsfile
pipeline {
    agent none
    stages {
        stage('Maven Build') {
            steps {
                script {
                    def statusCode = sh(script: 'mvn clean install', returnStatus: true)
                    if (statusCode > 0) {
                        currentBuild.result = 'FAILURE'
                        error 'Maven failed'
                    }
                }
            }
        }
        stage('Read File') {
            steps {
                script {
                    if (readFile('output') == 'FAILED!!!') {
                        currentBuild.result = 'FAILURE'
                        error 'Build failed'
                    }
                }
            }
        }
    }
}
