// Jenkinsfile
pipeline {
    agent none
    stages {
        stage('Maven Build') {
            agent { docker 'maven:3-alpine' }
            steps {
                sh('mvn clean install')
            }
        }
        stage('Read File') {
            steps {
                script {
                    if (readFile('output') == 'FAILED!!!') {
                        currentBuild.result = 'FAILURE'
                        error 'Build failed'
                    }
                }
            }
        }
    }
}
